using AddressUtility.Models.Base;
using Microsoft.EntityFrameworkCore;

namespace AddressUtility.Context.DataSeeding
{
    internal class SampleData
    {
        private readonly AddressObject[] objects = new AddressObject[]
        {
            new() { Id = 375856, Name = "Черноморское побережье Кавказа", TypeId = 1, RegionId = 93 },
            new() { Id = 17542, Name = "Новороссийск", ParentObjectId = 375856, TypeId = 3, AtomId = 13 },
            new() { Id = 411613, Name = "Южный", ParentObjectId = 17542, TypeId = 2, AtomId = 16 },
            new() { Id = 450436, Name = "16", ParentObjectId = 411613, TypeId = 10, AtomId = 21 },
            new() { Id = 449160, Name = "Южная", ParentObjectId = 450436, TypeId = 4, AtomId = 10 },

            new() { Id = 40133, Name = "Республика Татарстан", TypeId = 1, RegionId = 16 },
            new() { Id = 308208, Name = "Зеленодольский", ParentObjectId = 40133, TypeId = 2, AtomId = 16 },
            new() { Id = 308456, Name = "Бакрче", ParentObjectId = 308208, TypeId = 3, AtomId = 15 },
            new() { Id = 308699, Name = "Заря", ParentObjectId = 308456, TypeId = 4, AtomId = 10 },

            new() { Id = 401614, Name = "Челябинская область", TypeId = 1, RegionId = 74 },
            new() { Id = 401615, Name = "Челябинск", ParentObjectId = 401614, TypeId = 3, AtomId = 13 },
            new() { Id = 405364, Name = "Советский", ParentObjectId = 401615, TypeId = 2, AtomId = 16 },
            new() { Id = 447344, Name = "Новосинеглазово", ParentObjectId = 405364, TypeId = 3, AtomId = 14 },
            new() { Id = 403083, Name = "Односторонняя", ParentObjectId = 447344, TypeId = 4, AtomId = 10 }
        };

        private readonly AddrType[] types = new AddrType[]
        {
            new() { Id = 1, Name = "Административная единица", IsRegion = true },
            new() { Id = 2, Name = "Район", IsDistrict = true },
            new() { Id = 3, Name = "Населенный пункт", IsCity = true },
            new() { Id = 4, Name = "Улица", IsStreet = true },
            new() { Id = 5, Name = "Метро", IsTransportation = true },
            new() { Id = 6, Name = "Ж/д станция", IsTransportation = true },
            new() { Id = 7, Name = "Город - административная единица", IsRegion = true, IsCity = true },
            new() { Id = 8, Name = "Страна", IsRegion = true },
            new() { Id = 9, Name = "Город - административный центр", IsDistrict = true, IsCity = true },
            new() { Id = 10, Name = "Микрорайон" },
            new() { Id = 11, Name = "Округ", IsDistrict = true }
        };
        private readonly Atom[] atoms = new Atom[]
        {
            new() { Id = 1, Name = "м.", Description = "метро", Priority = 2 },
            new() { Id = 2, Name = "алл.", Description = "аллея", Priority = 7 },
            new() { Id = 3, Name = "бул.", Description = "бульвар", Priority = 7 },
            new() { Id = 4, Name = "дор.", Description = "дорога", Priority = 6 },
            new() { Id = 5, Name = "наб.", Description = "набережная", Priority = 8 },
            new() { Id = 6, Name = "пер.", Description = "переулок", Priority = 6 },
            new() { Id = 7, Name = "пл.", Description = "площадь", Priority = 1 },
            new() { Id = 8, Name = "пр.", Description = "проспект", Priority = 10 },
            new() { Id = 9, Name = "прд.", Description = "проезд", Priority = 1 },
            new() { Id = 10, Name = "ул.", Description = "улица", Priority = 9 },
            new() { Id = 11, Name = "шос.", Description = "шоссе", Priority = 8 },
            new() { Id = 12, Name = "дер.", Description = "деревня", Priority = 2 },
            new() { Id = 13, Name = "г.", Description = "город", Priority = 10 },
            new() { Id = 14, Name = "п.", Description = "поселок", Priority = 5 },
            new() { Id = 15, Name = "село", Description = "село", Priority = 4 },
            new() { Id = 16, Name = "р-н", Description = "район", Priority = 5 },
            new() { Id = 17, Name = "о-в", Description = "остров", Priority = 1 },
            new() { Id = 18, Name = "туп.", Description = "тупик", Priority = 1 },
            new() { Id = 19, Name = "кан.", Description = "канал", Priority = 1 },
            new() { Id = 20, Name = "ж/д", Description = "железнодорожная станция", Priority = 1 },
            new() { Id = 21, Name = "мкр.", Description = "микрорайон", Priority = 4 },
            new() { Id = 22, Name = "в-ть", Description = "волость", Priority = 1 },
            new() { Id = 23, Name = "сад-во", Description = "садоводство", Priority = 4 },
            new() { Id = 24, Name = "пгт.", Description = "поселок городского типа", Priority = 6 },
            new() { Id = 25, Name = "промзона", Description = "промзона", Priority = 1 },
            new() { Id = 26, Name = "дп", Description = "дачный поселок", Priority = 3 },
            new() { Id = 27, Name = "кп", Description = "курортный поселок", Priority = 3 },
            new() { Id = 28, Name = "п/о", Description = "почтовое отделение", Priority = 1 },
            new() { Id = 29, Name = "рп", Description = "рабочий поселок", Priority = 2 },
            new() { Id = 30, Name = "городок", Description = "городок", Priority = 1 },
            new() { Id = 31, Name = "мест.", Description = "местечко", Priority = 1 },
            new() { Id = 32, Name = "нп", Description = "населенный пункт", Priority = 1 },
            new() { Id = 33, Name = "п/ст", Description = "поселок и(при) станция(и)", Priority = 1 },
            new() { Id = 34, Name = "рзд.", Description = "разъезд", Priority = 1 },
            new() { Id = 35, Name = "ст.", Description = "станция", Priority = 1 },
            new() { Id = 36, Name = "х.", Description = "хутор", Priority = 1 },
            new() { Id = 37, Name = "тер.", Description = "территория", Priority = 2 },
            new() { Id = 38, Name = "казарма", Description = "казарма", Priority = 1 },
            new() { Id = 39, Name = "заезд", Description = "заезд", Priority = 1 },
            new() { Id = 40, Name = "кв-л", Description = "квартал", Priority = 2 },
            new() { Id = 41, Name = "км", Description = "километр", Priority = 4 },
            new() { Id = 42, Name = "линия", Description = "линия", Priority = 8 },
            new() { Id = 43, Name = "парк", Description = "парк", Priority = 1 },
            new() { Id = 44, Name = "переезд", Description = "переезд", Priority = 1 },
            new() { Id = 45, Name = "просек", Description = "просек", Priority = 1 },
            new() { Id = 46, Name = "тракт", Description = "тракт", Priority = 1 },
            new() { Id = 47, Name = "сад", Description = "сад", Priority = 1 },
            new() { Id = 48, Name = "свх.", Description = "совхоз", Priority = 1 },
            new() { Id = 49, Name = "с. о.", Description = "сельский округ", Priority = 1 },
            new() { Id = 51, Name = "автодорога", Description = "автодорога", Priority = 11 },
            new() { Id = 52, Name = "просека", Description = "просека", Priority = 11 },
            new() { Id = 53, Name = "путепровод", Description = "путепровод", Priority = 11 },
            new() { Id = 54, Name = "адм. округ", Description = "административный округ", Priority = 12 },
            new() { Id = 55, Name = "проулок", Description = "проулок", Priority = 12 },
            new() { Id = 56, Name = "c.п.", Description = "сельское поселение", Priority = 12 },
            new() { Id = 57, Name = "сл", Description = "слобода", Priority = 12 },
            new() { Id = 58, Name = "спуск", Description = "спуск", Priority = 12 },
            new() { Id = 59, Name = "ст-ца", Description = "станица", Priority = 5 },
            new() { Id = 60, Name = "аул", Description = "аул", Priority = 1 },
            new() { Id = 61, Name = "ж/д_рзд", Description = "железнодорожный разъезд", Priority = 1 },
            new() { Id = 62, Name = "погост", Description = "погост", Priority = 1 },
            new() { Id = 63, Name = "полустанок", Description = "полустанок", Priority = 1 },
            new() { Id = 64, Name = "г.п.", Description = "поселение", Priority = 1 },
            new() { Id = 65, Name = "снт", Description = "садов-е неком-е товарищество", Priority = 1 },
            new() { Id = 66, Name = "стр", Description = "строение", Priority = 1 },
            new() { Id = 67, Name = "уч-к", Description = "участок", Priority = 1 },
            new() { Id = 68, Name = "ферма", Description = "ферма", Priority = 1 },
            new() { Id = 69, Name = "пляж", Description = "пляж", Priority = 5 },
            new() { Id = 70, Name = "улус", Description = "улус", Priority = 5 },
            new() { Id = 71, Name = "горка", Description = "горка", Priority = 9 },
            new() { Id = 72, Name = "маяк", Description = "маяк", Priority = 9 },
            new() { Id = 73, Name = "тоннель", Description = "тоннель", Priority = 9 },
            new() { Id = 74, Name = "авт.окр.", Description = "автономный округ", Priority = 12 },
            new() { Id = 75, Name = "м.о.", Description = "муниципальный округ", Priority = 5 },
            new() { Id = 76, Name = "коттедж.п.", Description = "коттеджный поселок", Priority = 5 }
        };
        private readonly Region[] regions = new Region[]
        {
            new() { Id = 2, Name = "Башкортостан Республика", ShortName = "Уфа" },
            new() { Id = 3, Name = "Республика Бурятия", ShortName = "Бурятия" },
            new() { Id = 4, Name = "Республика Алтай", ShortName = "Алтай" },
            new() { Id = 5, Name = "Республика Дагестан", ShortName = "Дагестан" },
            new() { Id = 6, Name = "Республика Ингушетия", ShortName = "Ингушетия" },
            new() { Id = 7, Name = "Кабардино-Балкарская республика", ShortName = "Кабардино-Балкария" },
            new() { Id = 8, Name = "Республика Калмыкия", ShortName = "Калмыкия" },
            new() { Id = 9, Name = "Карачаево-Черкесская республика", ShortName = "Карачаево-Черкессия" },
            new() { Id = 10, Name = "Республика Карелия", ShortName = "Карелия" },
            new() { Id = 11, Name = "Республика Коми", ShortName = "Сыктывкар" },
            new() { Id = 12, Name = "Республика Марий Эл", ShortName = "Марий Эл" },
            new() { Id = 13, Name = "Республика Мордовия", ShortName = "Мордовия" },
            new() { Id = 14, Name = "Республика Саха (Якутия)", ShortName = "Якутия" },
            new() { Id = 15, Name = "Республика Северная Осетия - Алания", ShortName = "Осетия" },
            new() { Id = 16, Name = "Республика Татарстан", ShortName = "Казань" },
            new() { Id = 17, Name = "Республика Тыва", ShortName = "Тыва" },
            new() { Id = 18, Name = "Удмуртская Республика", ShortName = "Ижевск" },
            new() { Id = 19, Name = "Республика Хакасия", ShortName = "Хакасия" },
            new() { Id = 20, Name = "Чеченская республика", ShortName = "Чечня" },
            new() { Id = 21, Name = "Чувашская Республика", ShortName = "Чебоксары" },
            new() { Id = 22, Name = "Алтайский край", ShortName = "Барнаул" },
            new() { Id = 23, Name = "Краснодарский край и Республика Адыгея", ShortName = "Краснодар" },
            new() { Id = 24, Name = "Красноярский Край", ShortName = "Красноярск" },
            new() { Id = 25, Name = "Приморский край", ShortName = "Владивосток" },
            new() { Id = 26, Name = "Ставропольский край", ShortName = "Ставрополь" },
            new() { Id = 27, Name = "Хабаровский край", ShortName = "Хабаровск" },
            new() { Id = 28, Name = "Амурская область", ShortName = "Амурская область" },
            new() { Id = 29, Name = "Архангельская область", ShortName = "Архангельск" },
            new() { Id = 30, Name = "Астраханская область", ShortName = "Астрахань" },
            new() { Id = 31, Name = "Белгородская область", ShortName = "Белгород" },
            new() { Id = 32, Name = "Брянская область", ShortName = "Брянск" },
            new() { Id = 33, Name = "Владимирская область", ShortName = "Владимир" },
            new() { Id = 34, Name = "Волгоградская область", ShortName = "Волгоград" },
            new() { Id = 35, Name = "Вологодская область", ShortName = "Вологда" },
            new() { Id = 36, Name = "Воронежская область", ShortName = "Воронеж" },
            new() { Id = 37, Name = "Ивановская область", ShortName = "Иваново" },
            new() { Id = 38, Name = "Иркутская область", ShortName = "Иркутск" },
            new() { Id = 39, Name = "Калининградская область", ShortName = "Калининград" },
            new() { Id = 40, Name = "Калужская область", ShortName = "Калуга" },
            new() { Id = 41, Name = "Камчатский край", ShortName = "Камчатка" },
            new() { Id = 42, Name = "Кемеровская область", ShortName = "Кемерово" },
            new() { Id = 43, Name = "Кировская область", ShortName = "Киров" },
            new() { Id = 44, Name = "Костромская область", ShortName = "Кострома" },
            new() { Id = 45, Name = "Курганская область", ShortName = "Курганская область" },
            new() { Id = 46, Name = "Курская область", ShortName = "Курск" },
            new() { Id = 48, Name = "Липецкая область", ShortName = "Липецк" },
            new() { Id = 49, Name = "Магаданская область", ShortName = "Магадан" },
            new() { Id = 51, Name = "Мурманская область", ShortName = "Мурманск" },
            new() { Id = 52, Name = "Нижегородская область", ShortName = "Нижний Новгород" },
            new() { Id = 53, Name = "Новгородская область", ShortName = "Великий Новгород" },
            new() { Id = 54, Name = "Новосибирская область", ShortName = "Новосибирск" },
            new() { Id = 55, Name = "Омская область", ShortName = "Омск" },
            new() { Id = 56, Name = "Оренбургская область", ShortName = "Оренбург" },
            new() { Id = 57, Name = "Орловская область", ShortName = "Орёл" },
            new() { Id = 58, Name = "Пензенская область", ShortName = "Пенза" },
            new() { Id = 59, Name = "Пермский край", ShortName = "Пермь" },
            new() { Id = 60, Name = "Псковская область", ShortName = "Псков" },
            new() { Id = 61, Name = "Ростовская область", ShortName = "Ростов-на-Дону" },
            new() { Id = 62, Name = "Рязанская область", ShortName = "Рязань" },
            new() { Id = 63, Name = "Самарская область", ShortName = "Самара" },
            new() { Id = 64, Name = "Саратовская область", ShortName = "Саратов" },
            new() { Id = 65, Name = "Сахалинская область", ShortName = "Сахалинская область" },
            new() { Id = 66, Name = "Свердловская область", ShortName = "Екатеринбург" },
            new() { Id = 67, Name = "Смоленская область", ShortName = "Смоленск" },
            new() { Id = 68, Name = "Тамбовская область", ShortName = "Тамбовская область" },
            new() { Id = 69, Name = "Тверская область", ShortName = "Тверь" },
            new() { Id = 70, Name = "Томская область", ShortName = "Томская область" },
            new() { Id = 71, Name = "Тульская область", ShortName = "Тула" },
            new() { Id = 72, Name = "Тюменская область", ShortName = "Тюмень" },
            new() { Id = 73, Name = "Ульяновская область", ShortName = "Ульяновск" },
            new() { Id = 74, Name = "Челябинская область", ShortName = "Челябинск" },
            new() { Id = 75, Name = "Забайкальский край", ShortName = "Забайкальский край" },
            new() { Id = 76, Name = "Ярославская область", ShortName = "Ярославль" },
            new() { Id = 77, Name = "Москва и область", ShortName = "Москва" },
            new() { Id = 78, Name = "Санкт-Петербург и область", ShortName = "Санкт-Петербург" },
            new() { Id = 79, Name = "Еврейская автономная область", ShortName = "Еврейская автономная область" },
            new() { Id = 83, Name = "Ненецкий автономный округ", ShortName = "Ненецкий автономный округ" },
            new() { Id = 86, Name = "Ханты-Мансийский автономный округ", ShortName = "Ханты-Мансийск" },
            new() { Id = 87, Name = "Чукотский автономный округ", ShortName = "Чукотский автономный округ" },
            new() { Id = 89, Name = "Ямало-Ненецкий автономный округ", ShortName = "Ямало-Ненецкий автономный округ" },
            new() { Id = 91, Name = "Республика Крым", ShortName = "Крым" },
            new() { Id = 93, Name = "Черноморское побережье Кавказа", ShortName = "Черноморское побережье" },
            new() { Id = 201, Name = "Таиланд", ShortName = "Таиланд" }
        };

        public void Seed(ModelBuilder builder)
        {
            builder.Entity<AddressObject>().HasData(objects);
            builder.Entity<AddrType>().HasData(types);
            builder.Entity<Atom>().HasData(atoms);
            builder.Entity<Region>().HasData(regions);
        }
    }
}
